### ISSUE TITLE
Regional Attention and Neighborhood Attention

### ISSUE THREAD

**Issue by zyt0929** [CalcuLuUus/RASM#5]
What is the difference between Neighborhood Attention and Regional Attention?
 I see that the formulas in your paper are the same as those in Neighborhood Attention. What modifications have you made.

**Comment by CalcuLuUus** [comment]
Hello! Thank you for your interest in our work.  

Our approach emphasizes "allowing each shadowed region to focus on the unique non-shadowed information adjacent to it." The proposed Regional Attention mechanism is designed to attend to both shadowed and non-shadowed areas, facilitating information exchange between these distinct regions. Figure 6 in the paper also demonstrates the effectiveness of Regional Attention. This is fundamentally different from the starting point and core idea of Neighborhood Attention.  

We will continue to improve RASM in the future, and we welcome you to follow our work.

**Comment by CalcuLuUus** [comment]
If you have any other questions, feel free to ask!

**Comment by ZHUXIUJINChris** [comment]
Thank you for your excellent work!

Could you further explain the difference between the Neighborhood Attention and the Regional Attention? I apologize, but I couldn't fully understand your explanation above.

Additionally, have you considered incorporating or integrating the SIA mechanism from Shadowformer?

**Comment by zyt0929** [comment]
I wasn't the only one who didn't understand the difference between NA and RA, and I couldn't understand the author's response either.
 My understanding is that NA can be used for universal tasks such as recognition, detection, and segmentation, while RA can only be used for shadow removal tasks.
 The reason for the difference between RA and NA is that the shadow image is segmented into two parts by the mask.

**Comment by ZHUXIUJINChris** [comment]
My understanding is that NA and RA have no structural or content differences, but the combination in RASM is made up of the CA Module and RA Module. The RA Module processes downsampled features, enabling interaction both inside and outside shadow regions without being constrained by windows, thereby improving performance. 

However, I am curious why this approach would outperform the SIA mechanism in ShadowFormer. Intuitively, ShadowFormer seems more reasonable—perhaps this is a case of brute force yielding unexpected results. 

I’m not sure if my guess is accurate, and I’d appreciate any corrections if I’m mistaken.

**Comment by lime-j** [comment]
> My understanding is that NA and RA have no structural or content differences, but the combination in RASM is made up of the CA Module and RA Module. The RA Module processes downsampled features, enabling interaction both inside and outside shadow regions without being constrained by windows, thereby improving performance.
> 
> However, I am curious why this approach would outperform the SIA mechanism in ShadowFormer. Intuitively, ShadowFormer seems more reasonable—perhaps this is a case of brute force yielding unexpected results.
> 
> I’m not sure if my guess is accurate, and I’d appreciate any corrections if I’m mistaken.

Thanks for your attention to our work, and sorry for the late reply. 

Your understanding is mostly correct. We found that it is vital for interaction within the neighborhood area instead of pre-defined windows. Since ShadowFormer's SIA module enhances the interaction within the shadow area by reweighting the attention matrix in each window, I think It's okay if you combine Regional Attention with ShadowFormer's reweighting scheme. 

However,  I guess the performance may not improve (I would love to conduct experiments for it, but we are too busy and don't have enough bandwidth).  

Attention-based modules in shadow removal require not only shadow-to-shadow interaction(S2S in short) but also non-shadow-to-shadow(NS2S) interaction, which determines how much gain should be taken to refine shadow areas into non-shadow ones. This variant can be done with a multi-head mechanism in self-attention, where different head makes interests with different types of interaction. 

ShadowFormer makes the pioneering step towards "enhances the interaction in attention matrix", but if you force all heads to focus on S2S interaction, the NS2S interaction will be ignored. Therefore, I think their method is more likely a case of brute force.

We believe in another principle: instead of forcing the model to have a specific type of interaction, we construct everything they need (proper data augmentation, reasonable learning rate/optimizer, and most importantly, an architecture that doesn't block the information flow), and let the model learn the correct interaction. In fact, if you visualize the attention matrix inside the RASM, you will find not only S2S interaction, but also NS2S interaction can be learned correctly.
