### ISSUE TITLE
help

### ISSUE THREAD

**Issue by zyt0929** [CalcuLuUus/RASM#6]
Hello, I saw the reviewer's question to you: Which part of your model promotes lightweighting?
 Did adding an RA module parameter to your model, which was modified on ShadowFormer, make it smaller?
 I would like to know: 
1.   If RA is removed 
2.   If RA is replaced with window attention,
what are the changes in parameter size in these two cases.
 By the way, your ablation experiment was too simple.

**Comment by lime-j** [comment]
If you have a clear understanding of the transformer, you would realize that the attention reweighting design in ShadowFormer is sub-optimal, since it only encourages interaction within the shadow area. Our RA module is based on the vanilla window attention instead of SIA. Thanks to the effectiveness of regional attention, we can shrink the parameter count in convolution layers to reach a reasonable level of accuracy.  

We are glad to see that you read the OpenReview page. There are more detailed explanations in the supplementary file and our author-rebuttal file. It should be noted that our ablation experiment successfully supports our claim, as recognized by reviewers and area chairs. 

As a kindly reminder, you should note that nobody is obligated to respond to questions, especially those with clear answers in the code release, paper, and supplementary files. If you insist on asking, just be polite and remain grateful since we have spent our time explaining your question, amid the heavy workload we are facing with.

**Comment by ZHUXIUJINChris** [comment]
Thank you for your excellent work! 

Could you further explain the difference between the Neighborhood Attention and the Regional Attention? I apologize, but I couldn't fully understand your explanation above.

Additionally, have you considered incorporating or integrating the SIA mechanism from Shadowformer?
